version: 2 # use CircleCI 2.0

deploy_config: &deploy_config
  docker:
    - image: circleci/python:latest
  working_directory: ~/app

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:lts # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: Update npm to latest
          command: "sudo npm install -g npm@latest"
  deploy_prod: 
        docker:
            - image: circleci/node:lts
        working_directory: ~/app/
        steps:
            - checkout
            - run:
                name: npm install
                command: npm install
            - run:
                name: Install awscli
                command: 'sudo apt-get install -y python-pip python-dev && sudo rm -rf /var/lib/apt/lists/* && sudo pip install awscli'
            - run:
                name: Deploy Images to S3
                command: aws s3 sync images/ s3://images.thisisblaze.com --delete --acl public-read
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy_approve:
          type: approval
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - deploy_prod:
          requires:
            - build
            - deploy_approve
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/